# Generated by Django 3.1.3 on 2020-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201119_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='app.Tag', verbose_name='Теги'),
        ),
    ]
